from __future__ import annotations

SCENE_TEMPLATE = """from manim import *
import numpy as np

# Generated by Manim GUI Builder (scene JSON is source of truth)
{preamble}


class GeneratedScene(Scene):
    def construct(self):
{body}
"""
